--Eliminar los registros de la tabla
DELETE FROM curso;

-- Insertar datos en la tabla Curso
INSERT INTO curso (CurCod, CurNom, CurNumMod, CurFre, CurEstRegCod)
VALUES
    (105, 'Comunicación de Peligros: Básico', 0, False, 1),
    (107, 'Planes de Actuación de Emergencias y Prevención de Incendios', 0, False, 1),
    (108, 'Equipo de Protección Personal: Básico', 0, False, 1),
    (112, 'Introducción a la Supervisión de Seguridad', 0, False, 1),
    (113, 'Introducción al Liderazgo en Seguridad', 0, False, 1),
    (114, 'Superficies para Caminar-Trabajar y Protección Contra Caídas', 0, False, 1),
    (115, 'Seguridad Eléctrica para Empleados: Básico', 0, False, 1),
    (116, 'Introducción a la Responsabilidad de Seguridad', 0, False, 1),
    (117, 'Introducción al Reconocimiento de Seguridad', 0, False, 1),
    (119, 'Seguridad del Conductor', 0, False, 1),
    (120, 'Seguridad en los Almacenes', 0, False, 1),
    (121, 'Introducción a la Formación en Seguridad', 0, False, 1),
    (122, 'Introducción a los Controles de Riesgos', 0, False, 1),
    (123, 'Introducción al Análisis de Riesgos Laborales', 0, False, 1),
    (138, 'Higiene en el Lugar de Trabajo y Prevención de Enfermedades', 0, False, 1),
    (139, 'Orientaciones para la Limpieza y la Desinfección', 0, False, 1),
    (144, 'Introducción a OSHA', 0, False, 1),
    (150, 'Riesgos Físicos para la Salud en la Construcción', 0, False, 1),
    (151, 'Peligros Biológicos para la Salud en la Construcción', 0, False, 1),
    (152, 'Riesgos Ergonómicos en la Construcción', 0, False, 1),
    (153, 'Riesgos Ergonómicos en la Industria General', 0, False, 1),
    (154, 'Protección de Máquinas: Básico', 0, False, 1),
    (155, 'Seguridad en la Soldadura: Básico', 0, False, 1),
    (156, 'Seguridad en Montacargas: Básico', 0, False, 1),
    (157, 'Seguridad en Excavación: Básico', 0, False, 1),
    (158, 'Seguridad de la Grúa: Básico', 0, False, 1),
    (159, 'Protección Auditiva: Básico', 0, False, 1),
    (161, 'Higiene Industrial: Básico', 0, False, 1),
    (162, 'Investigación de Accidentes: Básico', 0, False, 1),
    (170, 'Atención Sanitaria: Alergia al Látex', 0, False, 1),
    (171, 'Atención Sanitaria: Productos Químicos Peligrosos', 0, False, 1),
    (172, 'Atención Sanitaria: Seguridad del Glutaraldehído', 0, False, 1),
    (173, 'Atención Sanitaria: Seguridad del Mercurio', 0, False, 1),
    (174, 'Atención Sanitaria: Seguridad Contra Incendios', 0, False, 1),
    (175, 'Atención Sanitaria: Riesgos Biológicos', 0, False, 1),
    (176, 'Atención Sanitaria: Estrés y Violencia en el Lugar de Trabajo', 0, False, 1),
    (177, 'Sanidad: Seguridad Eléctrica', 0, False, 1),
    (178, 'Atención Sanitaria: Equipo de Protección Personal', 0, False, 1),
    (183, 'Atención Sanitaria: Seguridad Radiológica', 0, False, 1),
    (603, 'Seguridad en Escaleras', 0, False, 1),
    (604, 'Seguridad en Andamios', 0, False, 1),
    (605, 'Seguridad en Espacios Confinados', 0, False, 1),
    (611, 'Seguridad con Pistolas de Clavos', 0, False, 1),
    (612, 'Seguridad Vial en las Zonas de trabajo', 0, False, 1),
    (623, 'Prevención de Lesiones Ergonómicas', 0, False, 1),
    (624, 'Atención Médica: Prevención de Resbalones, Tropezones y Caídas', 0, False, 1),
    (656, 'Patógenos Transmitidos por la Sangre: en el Entorno Sanitario', 0, False, 1),
    (660, 'HAZWOPER para Trabajadores de Obras en General I', 0, False, 1),
    (661, 'HAZWOPER para Trabajadores de Obras en General II', 0, False, 1),
    (662, 'HAZWOPER para Trabajadores de Obras en General III', 0, False, 1),
    (663, 'HAZWOPER para Trabajadores de Obras en General IV', 0, False, 1),
    (664, 'HAZWOPER para Trabajadores de Obras en General V', 0, False, 1),
    (665, 'HAZWOPER para Trabajadores de Obras en General VI', 0, False, 1),
    (666, 'HAZWOPER para Trabajadores de Obras en General VII', 0, False, 1),
    (667, 'HAZWOPER para Trabajadores de Obras en General VIII', 0, False, 1),
    (668, 'HAZWOPER para Trabajadores de Obras en General IX', 0, False, 1),
    (669, 'HAZWOPER para Trabajadores de Obras en General X', 0, False, 1),
    (700, 'Introducción a la Gestión de la Seguridad', 0, False, 1),
    (702, 'Investigación Eficaz de Accidentes', 0, False, 1),
    (703, 'Introducción a la Formación en OSH', 0, False, 1),
    (704, 'Análisis y Control de Riesgos', 0, False, 1),
    (705, 'Programa de Comunicación de Riesgos', 0, False, 1),
    (706, 'Realización de un Análisis de Riesgos Laborales (JHA)', 0, False, 1),
    (709, 'Equipo de Protección Personal', 0, False, 1),
    (710, 'Programa de Control de Energía (Bloqueo/Etiquetado)', 0, False, 1),
    (711, 'Introducción a la Ergonomía', 0, False, 1),
    (713, 'Programa de Espacios Confinados', 0, False, 1),
    (714, 'Programa de Protección Contra Caídas', 0, False, 1),
    (715, 'Seguridad Eléctrica: para Técnicos y Supervisores', 0, False, 1),
    (716, 'Evaluación del Sistema de Gestión de Seguridad', 0, False, 1),
    (717, 'Planes de Acción de Emergencia', 0, False, 1),
    (718, 'Planes de Prevención de Incendios', 0, False, 1),
    (719, 'Gestión de Seguridad de Flotas', 0, False, 1),
    (721, 'Desarrollo de Capacitación en OSH', 0, False, 1),
    (723, 'Realización de capacitación en OSH', 0, False, 1),
    (725, 'Gestión del Programa de Seguridad de Carretillas Elevadoras', 0, False, 1),
    (726, 'Introducción a la Protección de Máquinas', 0, False, 1),
    (757, 'Seguridad en el Laboratorio', 0, False, 1),
    (800, 'Introducción a la Gestión de la Seguridad en la Construcción', 0, False, 1),
    (802, 'Seguridad en Zanjas y Excavaciones', 0, False, 1),
    (803, 'Gestión del Programa de Seguridad de Andamios', 0, False, 1),
    (804, 'Montaje e Inspección de Andamios Seguros', 0, False, 1),
    (805, 'Protección Contra Caídas en la Construcción', 0, False, 1),
    (806, 'Enfoque cuatro: Riesgos de Caídas', 0, False, 1),
    (807, 'Enfoque cuatro: Atrapados entre Peligros', 0, False, 1),
    (808, 'Enfoque cuatro: Peligros de ser Golpeado', 0, False, 1),
    (809, 'Enfoque cuatro: Peligros de Electrocución', 0, False, 1),
    (810, 'Seguridad con Herramientas Manuales y Eléctricas', 0, False, 1),
    (813, 'Seguridad en el Lugar de Trabajo de Construcción', 0, False, 1),
    (814, 'Seguridad de la Maquinaria Pesada', 0, False, 1),
    (815, 'Seguridad en la Demolición', 0, False, 1),
    (816, 'Seguridad en Espacios Confinados en la Construcción', 0, False, 1),
    (817, 'Seguridad en la Construcción de Acero', 0, False, 1),
    (820, 'Seguridad de Grúas y Derricks I', 0, False, 1),
    (821, 'Seguridad de Grúas y Derricks II', 0, False, 1),
    (833, 'Desarrollo de un Sistema de Gestión de Seguridad en la Construcción', 0, False, 1),
    (850, 'Riesgos para la Salud en la Construcción', 0, False, 1),
    (900, 'Gestión de la Seguridad del Petróleo y Gas', 0, False, 1),
    (904, 'Inspección de Pozos de Petróleo y Gas ', 0, False, 1),
    (907, 'Introducción a SEMS II: 30 CFR 250.1900-1933', 0, False, 1),
    (908, 'Seguridad del Petróleo y el Gas en Alta Mar I', 0, False, 1),
    (909, 'Seguridad del Petróleo y el Gas en Alta Mar II', 0, False, 1),
    (1000, 'Trabajos en Altura para Techos', 0, False, 1),
    (1110, 'Sistema Globalmente Armonizado SGA', 0, False, 1),
    (1200, 'Química General en la Industria 1', 0, False, 1),
    (1201, 'Química Básica 2', 0, False, 1),
    (1203, 'Toxicología', 0, False, 1),
    (5555, 'Toxicocinética', 0, False, 1),
    (5556, 'Toxicodinamia', 0, False, 1),
    (5557, 'Tratamiento General del Paciente Intoxicado', 0, False, 1),
    (5558, 'Tratamientos Específicos', 0, False, 1),
    (5559, 'Hipoxias Tóxicas Monóxido de Carbono', 0, False, 1),
    (5560, 'Hipoxias Tóxicas por Cianuro', 0, False, 1),
    (5561, 'Hipoxias Tóxicas Metahemoglobinemia', 0, False, 1),
    (5562, 'Radiotoxicidad', 0, False, 1),
    (5563, 'Intoxicación con Etanol', 0, False, 1),
    (5564, 'Intoxicación con Metanol', 0, False, 1),
    (5565, 'Intoxicación con Glicoles', 0, False, 1),
    (5566, 'Hidrocarburos Generalidades', 0, False, 1),
    (5567, 'Hidrocarburos Alifáticos o Lineales', 0, False, 1),
    (5568, 'Hidrocarburos Alogenados Clorado', 0, False, 1),
    (5569, 'Hidrocarburos Cíclicos Aromáticos', 0, False, 1),
    (5570, 'Hidrocarburos Nitrogenados', 0, False, 1),
    (5571, 'Arsénico', 0, False, 1),
    (5572, 'Plomo', 0, False, 1),
    (5573, 'Mercurio', 0, False, 1),
    (5574, 'Cromo', 0, False, 1),
    (5575, 'Manganeso', 0, False, 1),
    (5576, 'Talio', 0, False, 1),
    (5577, 'Hierro', 0, False, 1),
    (5578, 'Organofosforados', 0, False, 1),
    (5579, 'Organoclorados', 0, False, 1),
    (5580, 'Dicumarinicus', 0, False, 1),
    (5581, 'Bipiridilos', 0, False, 1),
    (5582, 'Piretrinas', 0, False, 1);