--Eliminar los registros de la tabla
DELETE FROM curso;

-- Insertar datos en la tabla Curso
INSERT INTO curso (CurCod, CurNom, CurNumMod, CurEstRegCod)
VALUES
    (100, 'Introducción a OSHAcademy', 0, 1),
    (105, 'Comunicación de peligros: Básico', 0, 1),
    (107, 'Planes de Actuación de Emergencias y Prevención de Incendios', 0, 1),
    (108, 'Equipo de Protección Personal: Básico', 0, 1),
    (112, 'Introducción a la Supervisión de Seguridad', 0, 1),
    (113, 'Introducción al Liderazgo en Seguridad', 0, 1),
    (114, 'Superficies para caminar-trabajar y protección contra caídas', 0, 1),
    (115, 'Seguridad Eléctrica para Empleados: Básica', 0, 1),
    (116, 'Introducción a la responsabilidad en materia de seguridad', 0, 1),
    (117, 'Introducción al reconocimiento de seguridad', 0, 1),
    (119, 'Seguridad del conductor', 0, 1),
    (120, 'Seguridad en los almacenes', 0, 1),
    (121, 'Introducción a la Formación en Seguridad', 0, 1),
    (122, 'Introducción a los controles de peligros', 0, 1),
    (123, 'Introducción al análisis de riesgos laborales', 0, 1),
    (138, 'Higiene del Trabajo y Prevención de Enfermedades', 0, 1),
    (139, 'Orientaciones para la limpieza y la desinfección', 0, 1),
    (144, 'Introducción a OSHA', 0, 1),
    (150, 'Peligros para la salud física en la construcción', 0, 1),
    (151, 'Peligros biológicos para la salud en la construcción', 0, 1),
    (152, 'Riesgos ergonómicos en la construcción', 0, 1),
    (153, 'Riesgos ergonómicos en la industria general', 0, 1),
    (154, 'Protección de máquinas: básica', 0, 1),
    (155, 'Seguridad en la soldadura: básica', 0, 1),
    (156, 'Seguridad en montacargas: Básico', 0, 1),
    (157, 'Seguridad en la excavación: Básico', 0, 1),
    (158, 'Seguridad en grúas: básica', 0, 1),
    (159, 'Protección Auditiva: Básico', 0, 1),
    (160, 'Seguridad de herramientas: básica', 0, 1),
    (161, 'Higiene Industrial: Básica', 0, 1),
    (162, 'Investigación de Accidentes: Básico', 0, 1),
    (170, 'Atención sanitaria: Alergia al látex', 0, 1),
    (171, 'Atención sanitaria: productos químicos peligrosos', 0, 1),
    (172, 'Atención sanitaria: seguridad del glutaraldehído', 0, 1),
    (173, 'Atención sanitaria: seguridad contra el mercurio', 0, 1),
    (174, 'Atención sanitaria: seguridad contra incendios', 0, 1),
    (175, 'Atención sanitaria: peligros biológicos', 0, 1),
    (176, 'Atención sanitaria: estrés y violencia laboral', 0, 1),
    (177, 'Sanidad: Seguridad Eléctrica', 0, 1),
    (178, 'Atención sanitaria: Equipo de protección personal', 0, 1),
    (179, 'Atención médica: Introducción a los peligros hospitalarios comunes', 0, 1),
    (181, 'Atención médica: seguridad con objetos punzantes', 0, 1),
    (182, 'Atención sanitaria: seguridad del óxido de etileno', 0, 1),
    (183, 'Atención sanitaria: seguridad radiológica', 0, 1),
    (500, 'EM 385-1-1 (Capítulos 1-6): 2014', 0, 1),
    (501, 'EM 385-1-1 (Capítulos 7-13): 2014', 0, 1),
    (502, 'EM 385-1-1 (Capítulos 14-19): 2014', 0, 1),
    (503, 'EM 385-1-1 (Capítulos 20-26): 2014', 0, 1),
    (504, 'EM 385-1-1 (Capítulos 27-34): 2014', 0, 1),
    (600, 'Introducción a la Seguridad y Salud en el Trabajo', 0, 1),
    (601, 'Fundamentos de Seguridad y Salud en el Trabajo', 0, 1),
    (602, 'Seguridad contra el estrés por calor y frío', 0, 1),
    (603, 'Seguridad en escaleras y escaleras', 0, 1),
    (604, 'Seguridad en andamios', 0, 1),
    (605, 'Seguridad en espacios confinados', 0, 1),
    (610, 'Seguridad en la limpieza', 0, 1),
    (611, 'Seguridad con pistolas de clavos', 0, 1),
    (612, 'Seguridad del tráfico en la zona de trabajo', 0, 1),
    (613, 'Seguridad de los trabajadores en restaurantes', 0, 1),
    (614, 'Equipos de protección personal y salvamento', 0, 1),
    (615, 'Seguridad Eléctrica: Peligros y Controles', 0, 1),
    (617, 'Gestión de la Seguridad y la Salud: Industria General', 0, 1),
    (618, 'Gestión de la Seguridad y la Salud: Construcción', 0, 1),
    (619, 'Seguridad en el manejo de materiales', 0, 1),
    (621, 'Control de energía peligrosa (bloqueo/etiquetado)', 0, 1),
    (623, 'Prevención de lesiones ergonómicas', 0, 1),
    (624, 'Atención médica: prevención de resbalones, tropezones y caídas', 0, 1),
    (628, 'Atención médica: seguridad de la ecografía', 0, 1),
    (629, 'Planificación de emergencias en el lugar de trabajo', 0, 1),
    (630, 'Atención sanitaria: seguridad en farmacia', 0, 1),
    (655, 'Patógenos transmitidos por la sangre: en el lugar de trabajo', 0, 1),
    (656, 'Patógenos transmitidos por la sangre: en el ámbito sanitario', 0, 1),
    (660, 'HAZWOPER para trabajadores de sitio general I', 0, 1),
    (661, 'HAZWOPER para trabajadores de sitios generales II', 0, 1),
    (662, 'HAZWOPER para trabajadores de sitios generales III', 0, 1),
    (663, 'HAZWOPER para trabajadores generales del sitio IV', 0, 1),
    (664, 'HAZWOPER para trabajadores generales del sitio V', 0, 1),
    (665, 'HAZWOPER para trabajadores de sitio general VI', 0, 1),
    (666, 'HAZWOPER para trabajadores de sitios generales VII', 0, 1),
    (667, 'HAZWOPER para trabajadores de sitios generales VIII', 0, 1),
    (668, 'HAZWOPER para trabajadores generales del sitio IX', 0, 1),
    (669, 'HAZWOPER para trabajadores generales del sitio X', 0, 1),
    (700, 'Introducción a la Gestión de la Seguridad', 0, 1),
    (701, 'Operaciones efectivas del Comité de Seguridad', 0, 1),
    (702, 'Investigación efectiva de accidentes', 0, 1),
    (703, 'Introducción a la Formación en SST', 0, 1),
    (704, 'Análisis y Control de Peligros', 0, 1),
    (705, 'Programa de comunicación de peligros', 0, 1),
    (706, 'Realización de un análisis de riesgos laborales (JHA)', 0, 1),
    (707, 'Reuniones efectivas del Comité de SST', 0, 1),
    (708, 'Conceptos básicos del mantenimiento de registros de OSHA', 0, 1),
    (709, 'Equipo de Protección Personal', 0, 1),
    (710, 'Programa de control de energía (bloqueo/etiquetado)', 0, 1),
    (711, 'Introducción a la Ergonomía', 0, 1),
    (712, 'Supervisión y Liderazgo de Seguridad', 0, 1),
    (713, 'Programa de Espacios Confinados', 0, 1),
    (714, 'Programa de protección contra caídas', 0, 1),
    (715, 'Seguridad Eléctrica: para Técnicos y Supervisores', 0, 1),
    (716, 'Evaluación del Sistema de Gestión de Seguridad', 0, 1),
    (717, 'Planes de Acción de Emergencia', 0, 1),
    (718, 'Planes de Prevención de Incendios', 0, 1),
    (719, 'Gestión de Seguridad de Flotas', 0, 1),
    (720, 'Prevención de la violencia en el lugar de trabajo', 0, 1),
    (721, 'Desarrollo de Capacitación en SST', 0, 1),
    (722, 'Gestión del Programa de Ergonomía', 0, 1),
    (723, 'Realización de capacitación en SST', 0, 1),
    (725, 'Gestión del Programa de Seguridad de Montacargas', 0, 1),
    (726, 'Introducción a la protección de máquinas', 0, 1),
    (736, 'Introducción a la Gestión de la Seguridad de Procesos (PSM)', 0, 1),
    (744, 'Trabajar con OSHA', 0, 1),
    (750, 'Introducción a la Higiene Industrial', 0, 1),
    (751, 'Gestión del Programa de Conservación de la Audición', 0, 1),
    (755, 'Patógenos transmitidos por la sangre: gestión del programa', 0, 1),
    (757, 'Seguridad de laboratorio', 0, 1),
    (776, 'Prevención de la violencia laboral: en el sector sanitario', 0, 1),
    (800, 'Introducción a la Gestión de la Seguridad en la Construcción', 0, 1),
    (802, 'Seguridad en zanjas y excavaciones', 0, 1),
    (803, 'Gestión del Programa de Seguridad de Andamios', 0, 1),
    (804, 'Montaje e inspección segura de andamios', 0, 1),
    (805, 'Protección contra caídas en la construcción: elementos para 29 CFR 1926.500-503', 0, 1),
    (806, 'Enfoque cuatro: Peligros de caídas', 0, 1),
    (807, 'Enfoque cuatro: Atrapados entre peligros', 0, 1),
    (808, 'Enfoque cuatro: Peligros de ser golpeado', 0, 1),
    (809, 'Enfoque cuatro: Peligros de electrocución', 0, 1),
    (810, 'Seguridad con herramientas manuales y eléctricas', 0, 1),
    (812, 'Enfoque cuatro de OSHA', 0, 1),
    (813, 'Seguridad en el lugar de trabajo de construcción', 0, 1),
    (814, 'Seguridad de Equipo Pesado', 0, 1),
    (815, 'Seguridad en la demolición', 0, 1),
    (816, 'Seguridad en espacios confinados en la construcción', 0, 1),
    (820, 'Seguridad de Grúas y Cabrias I', 0, 1),
    (821, 'Seguridad en Grúas y Cabrias II', 0, 1),
    (833, 'Desarrollo de un sistema de gestión de seguridad en la construcción', 0, 1),
    (850, 'Riesgos para la Salud en la Construcción', 0, 1),
    (900, 'Gestión de la Seguridad del Petróleo y Gas', 0, 1),
    (901, 'Concientización sobre los peligros del petróleo y el gas', 0, 1),
    (902, 'Preparación del sitio del pozo y seguridad de la perforación', 0, 1),
    (903, 'Seguridad en la finalización y el mantenimiento del sitio del pozo', 0, 1),
    (904, 'Inspección de pozos de petróleo y gas ', 0, 1),
    (906, 'Limpieza de derrames de petróleo', 0, 1),
    (907, 'Introducción a SEMS II: 30 CFR 250.1900-1933', 0, 1),
    (908, 'Seguridad del petróleo y el gas costa afuera I', 0, 1),
    (909, 'Seguridad del petróleo y el gas costa afuera I', 0, 1),
    (1110, 'Sistema Globalmente Armonizado SGA', 0, 1),
    (1200, '', 0, 1),
    (1201, 'Química básica 2', 0, 1),
    (1203, 'Toxicología', 0, 1);
