--Eliminar los registros de la tabla
DELETE FROM curso;

-- Insertar datos en la tabla Curso
INSERT INTO curso (CurCod, CurNom, CurNomEng, CurNumMod, CurFre, CurEstRegCod)
VALUES
    (105, 'Comunicación de Peligros: Básico', 'Risk communication: Basic', 0, False, 1),
    (107, 'Planes de Actuación de Emergencias y Prevención de Incendios', 'Emergency Action and Fire Prevention Plans', 0, False, 1),
    (108, 'Equipo de Protección Personal: Básico', 'Individual protective equipment: Basic', 0, False, 1),
    (112, 'Introducción a la Supervisión de Seguridad', 'Introduction to Safety Supervision', 0, False, 1),
    (113, 'Introducción al Liderazgo en Seguridad', 'Introduction to Safety Leadership', 0, False, 1),
    (114, 'Superficies para Caminar-Trabajar y Protección Contra Caídas', ' Walking-Working Surfaces and Fall Protection', 0, False, 1),
    (115, 'Seguridad Eléctrica para Empleados: Básico', 'Electrical Safety for Employees: Basic',  0, False, 1),
    (116, 'Introducción a la Responsabilidad de Seguridad', 'Introduction to Safety Accountability', 0, False, 1),
    (117, 'Introducción al Reconocimiento de Seguridad', 'Introduction to Safety Recognition', 0, False, 1),
    (119, 'Seguridad del Conductor', 'Driver Safety', 0, False, 1),
    (120, 'Seguridad en los Almacenes', 'Warehouse Safety', 0, False, 1),
    (121, 'Introducción a la Formación en Seguridad', 'Introduction to Safety Training',  0, False, 1),
    (122, 'Introducción a los Controles de Riesgos', 'Introduction to Hazard Controls', 0, False, 1),
    (123, 'Introducción al Análisis de Riesgos Laborales', 'Introduction to Job Hazard Analysis', 0, False, 1),
    (138, 'Higiene en el Lugar de Trabajo y Prevención de Enfermedades', ' Workplace Hygiene and Illness Prevention', 0, False, 1),
    (139, 'Orientaciones para la Limpieza y la Desinfección', 'Guidance for Cleaning and Disinfecting', 0, False, 1),
    (144, 'Introducción a OSHA', 'Introduction to OSHA', 0, False, 1),
    (150, 'Riesgos Físicos para la Salud en la Construcción', 0, 'Physical Health Hazards in Construction', False, 1),
    (151, 'Peligros Biológicos para la Salud en la Construcción', 0, 'Biological Health Hazards in Construction', False, 1),
    (152, 'Riesgos Ergonómicos en la Construcción', 0, 'Ergonomic Hazards in Construction', False, 1),
    (153, 'Riesgos Ergonómicos en la Industria General', 'Ergonomic Hazards in General Industry', 0, False, 1),
    (154, 'Protección de Máquinas: Básico', 0, 'Machine Safeguarding: Basic', False, 1),
    (155, 'Seguridad en la Soldadura: Básico', 'Welding Safety: Basic', 0, False, 1),
    (156, 'Seguridad en Montacargas: Básico', 'Forklift Safety: Basic', 0, False, 1),
    (157, 'Seguridad en Excavación: Básico', 'Excavation Safety: Basic', 0, False, 1),
    (158, 'Seguridad de la Grúa: Básico', 'Crane Safety: Basic', 0, False, 1),
    (159, 'Protección Auditiva: Básico', 'Hearing Protection: Basic', 0, False, 1),
    (161, 'Higiene Industrial: Básico', ' Industrial Hygiene: Basic', 0, False, 1),
    (162, 'Investigación de Accidentes: Básico', 'Accident Investigation: Basic', 0, False, 1),
    (170, 'Atención Sanitaria: Alergia al Látex', ' Healthcare: Latex Allergy', 0, False, 1),
    (171, 'Atención Sanitaria: Productos Químicos Peligrosos', 'Healthcare: Hazardous Chemicals', 0, False, 1),
    (172, 'Atención Sanitaria: Seguridad del Glutaraldehído', 'Healthcare: Glutaraldehyde Safety', 0, False, 1),
    (173, 'Atención Sanitaria: Seguridad del Mercurio', 'Healthcare: Mercury Safety', 0, False, 1),
    (174, 'Atención Sanitaria: Seguridad Contra Incendios', 'Healthcare: Fire Safety', 0, False, 1),
    (175, 'Atención Sanitaria: Riesgos Biológicos', 'Healthcare: Biological Hazards', 0, False, 1),
    (176, 'Atención Sanitaria: Estrés y Violencia en el Lugar de Trabajo', 'Healthcare: Workplace Stress and Violence', 0, False, 1),
    (177, 'Sanidad: Seguridad Eléctrica', 'Healthcare: Electrical Safety', 0, False, 1),
    (178, 'Atención Sanitaria: Equipo de Protección Personal', 'Healthcare: Personal Protective Equipment', 0, False, 1),
    (183, 'Atención Sanitaria: Seguridad Radiológica', ' Healthcare: Radiation Safety', 0, False, 1),
    (603, 'Seguridad en Escaleras', 'Stairway and Ladder Safety', 0, False, 1),
    (604, 'Seguridad en Andamios', 'Scaffold Safety', 0, False, 1),
    (605, 'Seguridad en Espacios Confinados', 'Confined Space Safety', 0, False, 1),
    (611, 'Seguridad con Pistolas de Clavos', ' Nail Gun Safety', 0, False, 1),
    (612, 'Seguridad Vial en las Zonas de trabajo', 'Work Zone Traffic Safety', 0, False, 1),
    (623, 'Prevención de Lesiones Ergonómicas', 'Healthcare: Preventing Ergonomic Injuries', 0, False, 1),
    (624, 'Atención Médica: Prevención de Resbalones, Tropezones y Caídas', 'Healthcare: Slip, Trip, and Fall Prevention', 0, False, 1),
    (656, 'Patógenos Transmitidos por la Sangre: en el Entorno Sanitario', ' Bloodborne Pathogens in the Healthcare Setting', 0, False, 1),
    (660, 'HAZWOPER para Trabajadores de Obras en General I', 'HAZWOPER for General Site Workers I', 0, False, 1),
    (661, 'HAZWOPER para Trabajadores de Obras en General II', 'HAZWOPER for General Site Workers II', 0, False, 1),
    (662, 'HAZWOPER para Trabajadores de Obras en General III', 'HAZWOPER for General Site Workers III', 0, False, 1),
    (663, 'HAZWOPER para Trabajadores de Obras en General IV', ' HAZWOPER for General Site Workers IV', 0, False, 1),
    (664, 'HAZWOPER para Trabajadores de Obras en General V', 'HAZWOPER for General Site Workers V', 0, False, 1),
    (665, 'HAZWOPER para Trabajadores de Obras en General VI', 'HAZWOPER for General Site Workers VI', 0, False, 1),
    (666, 'HAZWOPER para Trabajadores de Obras en General VII', 'HAZWOPER for General Site Workers VII', 0, False, 1),
    (667, 'HAZWOPER para Trabajadores de Obras en General VIII', 'HAZWOPER for General Site Workers VIII', 0, False, 1),
    (668, 'HAZWOPER para Trabajadores de Obras en General IX', 'HAZWOPER for General Site Workers IX', 0, False, 1),
    (669, 'HAZWOPER para Trabajadores de Obras en General X', 'HAZWOPER for General Site Workers X', 0, False, 1),
    (700, 'Introducción a la Gestión de la Seguridad', 'Introduction to Safety Management', 0, False, 1),
    (702, 'Investigación Eficaz de Accidentes', 'Effective Accident Investigation', 0, False, 1),
    (703, 'Introducción a la Formación en OSH', 'Introduction to OSH Training', 0, False, 1),
    (704, 'Análisis y Control de Riesgos', 'Hazard Analysis and Control', 0, False, 1),
    (705, 'Programa de Comunicación de Riesgos', 'Hazard Analysis and Control', 0, False, 1),
    (706, 'Realización de un Análisis de Riesgos Laborales (JHA)', 'Conducting a Job Hazard Analysis', 0, False, 1),
    (709, 'Equipo de Protección Personal', 'Conducting a Job Hazard Analysis', 0, False, 1),
    (710, 'Programa de Control de Energía (Bloqueo/Etiquetado)', 'Energy Control Program (Lockout/Tagout)', 0, False, 1),
    (711, 'Introducción a la Ergonomía', 'Introduction to Ergonomics', 0, False, 1),
    (713, 'Programa de Espacios Confinados', 'Confined Space Program', 0, False, 1),
    (714, 'Programa de Protección Contra Caídas', 'Fall Protection Program', 0, False, 1),
    (715, 'Seguridad Eléctrica: para Técnicos y Supervisores', 'Electrical Safety for Technicians and Supervisors', 0, False, 1),
    (716, 'Evaluación del Sistema de Gestión de Seguridad', 'Safety Management System Evaluation', 0, False, 1),
    (717, 'Planes de Acción de Emergencia', 'Emergency Action Plans', 0, False, 1),
    (718, 'Planes de Prevención de Incendios', 'Fire Prevention Plans', 0, False, 1),
    (719, 'Gestión de Seguridad de Flotas', ' Fleet Safety Management', 0, False, 1),
    (721, 'Desarrollo de Capacitación en OSH', 'OSH Training Development', 0, False, 1),
    (723, 'Realización de capacitación en OSH', 'Conducting OSH Training', 0, False, 1),
    (725, 'Gestión del Programa de Seguridad de Carretillas Elevadoras', 'Forklift Safety Program Management', 0, False, 1),
    (726, 'Introducción a la Protección de Máquinas', 'Introduction to Machine Guarding', 0, False, 1),
    (757, 'Seguridad en el Laboratorio', 'Laboratory Safety', 0, False, 1),
    (800, 'Introducción a la Gestión de la Seguridad en la Construcción', 'Introduction to Construction Safety Management ', 0, False, 1),
    (802, 'Seguridad en Zanjas y Excavaciones', 'Trench and Excavation Safety ', 0, False, 1),
    (803, 'Gestión del Programa de Seguridad de Andamios', 'Scaffold Safety Program Management ', 0, False, 1),
    (804, 'Montaje e Inspección de Andamios Seguros', 'Safe Scaffold Erection and Inspection ', 0, False, 1),
    (805, 'Protección Contra Caídas en la Construcción', 'Fall Protection in Construction', 0, False, 1),
    (806, 'Enfoque cuatro: Riesgos de Caídas', 'Focus Four - Fall Hazards', 0, False, 1),
    (807, 'Enfoque cuatro: Atrapados entre Peligros', 'Focus Four: Caught In/Between Hazards', 0, False, 1),
    (808, 'Enfoque cuatro: Peligros de ser Golpeado', 'Focus Four - Struck-By Hazards', 0, False, 1),
    (809, 'Enfoque cuatro: Peligros de Electrocución', 'Focus Four - Electrocution Hazards', 0, False, 1),
    (810, 'Seguridad con Herramientas Manuales y Eléctricas', 'Hand and Power Tool Safety', 0, False, 1),
    (813, 'Seguridad en el Lugar de Trabajo de Construcción', 'Construction Worksite Safety', 0, False, 1),
    (814, 'Seguridad de la Maquinaria Pesada', 'Heavy Equipment Safety', 0, False, 1),
    (815, 'Seguridad en la Demolición', ' Demolition Safety', 0, False, 1),
    (816, 'Seguridad en Espacios Confinados en la Construcción', 'Confined Space Safety in Construction', 0, False, 1),
    (817, 'Seguridad en la Construcción de Acero', 'Steel Erection Safety', 0, False, 1),
    (820, 'Seguridad de Grúas y Derricks I', 'Cranes and Derricks Safety I', 0, False, 1),
    (821, 'Seguridad de Grúas y Derricks II', 'Cranes and Derricks Safety II', 0, False, 1),
    (833, 'Desarrollo de un Sistema de Gestión de Seguridad en la Construcción', 'Developing a Construction Safety Management System', 0, False, 1),
    (850, 'Riesgos para la Salud en la Construcción', 'Health Hazards in Construction', 0, False, 1),
    (900, 'Gestión de la Seguridad del Petróleo y Gas', ' Oil and Gas Safety Management', 0, False, 1),
    (904, 'Inspección de Pozos de Petróleo y Gas ', 'Oil and Gas Well Inspection', 0, False, 1),
    (907, 'Introducción a SEMS II: 30 CFR 250.1900-1933', ' Introduction to SEMS II', 0, False, 1),
    (908, 'Seguridad del Petróleo y el Gas en Alta Mar I', 'Offshore Oil and Gas Safety I', 0, False, 1),
    (909, 'Seguridad del Petróleo y el Gas en Alta Mar II', 'Offshore Oil and Gas Safety II', 0, False, 1),
    (1000, 'Trabajos en Altura para Techos', 'Work at Height for Roofs', 0, False, 1),
    (1110, 'Sistema Globalmente Armonizado SGA', 'Globally Harmonized System SGA', 0, False, 1),
    (1200, 'Química General en la Industria 1', 'General Chemistry in Industry I', 0, False, 1),
    (1201, 'Química Básica 2', 'Basic Chemistry II', 0, False, 1),
    (1203, 'Toxicología', 'Toxicology', 0, False, 1),
    (5555, 'Toxicocinética', 'Toxicokinetics', 0, False, 1),
    (5556, 'Toxicodinamia', 'Toxicodynamics', 0, False, 1),
    (5557, 'Tratamiento General del Paciente Intoxicado', 'General Treatment of the Intoxicated Patient', 0, False, 1),
    (5558, 'Tratamientos Específicos', 'Specific Treatments', 0, False, 1),
    (5559, 'Hipoxias Tóxicas Monóxido de Carbono', 'Toxic Hypoxia Carbon Monoxide', 0, False, 1),
    (5560, 'Hipoxias Tóxicas por Cianuro', 'Toxic Hypoxia due to Cyanide', 0, False, 1),
    (5561, 'Hipoxias Tóxicas Metahemoglobinemia', 'Toxic Hypoxia Methemoglobinemia', 0, False, 1),
    (5562, 'Radiotoxicidad', 'Radiotoxicity', 0, False, 1),
    (5563, 'Intoxicación con Etanol', 'Ethanol poisoning', 0, False, 1),
    (5564, 'Intoxicación con Metanol', 'Methanol poisoning', 0, False, 1),
    (5565, 'Intoxicación con Glicoles', 'Glycol poisoning', 0, False, 1),
    (5566, 'Hidrocarburos Generalidades', 'Hydrocarbons Generalities', 0, False, 1),
    (5567, 'Hidrocarburos Alifáticos o Lineales', 'Aliphatic or Linear Hydrocarbons', 0, False, 1),
    (5568, 'Hidrocarburos Alogenados Clorado', 'Chlorinated Halogenated Hydrocarbons', 0, False, 1),
    (5569, 'Hidrocarburos Cíclicos Aromáticos', 'Cyclic Aromatic Hydrocarbons', 0, False, 1),
    (5570, 'Hidrocarburos Nitrogenados', 'Nitrogenous Hydrocarbons', 0, False, 1),
    (5571, 'Arsénico', 'Arsenic', 0, False, 1),
    (5572, 'Plomo', 'Lead', 0, False, 1),
    (5573, 'Mercurio', 'Mercury', 0, False, 1),
    (5574, 'Cromo', 'Chrome', 0, False, 1),
    (5575, 'Manganeso', 'Manganese', 0, False, 1),
    (5576, 'Talio', 'Thallium', 0, False, 1),
    (5577, 'Hierro', 'Iron', 0, False, 1),
    (5578, 'Organofosforados', 'Organophosphates', 0, False, 1),
    (5579, 'Organoclorados', 'Organochlorines', 0, False, 1),
    (5580, 'Dicumarinicus', 'Dicumarinicus', 0, False, 1),
    (5581, 'Bipiridilos', 'Bipyridyls', 0, False, 1),
    (5582, 'Piretrinas', 'Pyrethrin', 0, False, 1);