# Generated by Django 5.0.3 on 2024-07-10 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoRegistro',
            fields=[
                ('estregcod', models.AutoField(db_column='EstRegCod', primary_key=True, serialize=False, verbose_name='Codigo')),
                ('estregnom', models.CharField(db_column='EstRegNom', max_length=40, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'EstadoRegistro',
                'verbose_name_plural': 'EstadosRegistro',
                'db_table': 'estado_registro',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstudianteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('estusernom', models.CharField(db_column='EstUserNom', max_length=60, verbose_name='Nombre')),
                ('estuserape', models.CharField(db_column='EstUserApe', max_length=60, verbose_name='Apellidos')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('curcod', models.IntegerField(db_column='CurCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('curnom', models.CharField(db_column='CurNom', max_length=80, verbose_name='Nombre')),
                ('curnummod', models.IntegerField(db_column='CurNumMod', default=0, verbose_name='Numero de módulos')),
                ('curestregcod', models.ForeignKey(db_column='CurEstRegCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.estadoregistro', verbose_name='Codigo EStReg')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'curso',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('estcod', models.AutoField(db_column='EstCod', primary_key=True, serialize=False, verbose_name='Codigo')),
                ('estnom', models.CharField(db_column='EstNom', max_length=60, verbose_name='Nombre')),
                ('estape', models.CharField(db_column='EstApe', max_length=60, verbose_name='Apellidos')),
                ('estdocide', models.CharField(db_column='EstDocIde', max_length=50, verbose_name='Documento de identidad')),
                ('estema', models.EmailField(db_column='EstEma', max_length=255, unique=True, verbose_name='Email')),
                ('estpai', models.CharField(blank=True, db_column='EstPai', max_length=50, verbose_name='Pais')),
                ('estciu', models.CharField(blank=True, db_column='EstCiu', max_length=50, verbose_name='Ciudad')),
                ('estdir', models.CharField(blank=True, db_column='EstDir', max_length=100, verbose_name='Direccion')),
                ('estestregcod', models.ForeignKey(db_column='EstEstReg', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='aula.estadoregistro')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiante',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('exacod', models.AutoField(db_column='ExaCod', primary_key=True, serialize=False, verbose_name='Codigo')),
                ('exacurcod', models.ForeignKey(db_column='ExaCurCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.curso', verbose_name='Codigo Curso')),
                ('exaestregcod', models.ForeignKey(db_column='ExaEstRegCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.estadoregistro', verbose_name='Codigo EStReg')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examenes',
                'db_table': 'examen',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('modcod', models.AutoField(db_column='ModCod', primary_key=True, serialize=False, verbose_name='Codigo')),
                ('modnom', models.CharField(db_column='ModNom', max_length=100, verbose_name='Nombre')),
                ('modcurcod', models.ForeignKey(db_column='ModCurCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.curso', verbose_name='Codigo Curso')),
                ('modestregcod', models.ForeignKey(db_column='ModEstRegCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.estadoregistro', verbose_name='Codigo EstReg')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
                'db_table': 'modulo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('precod', models.AutoField(db_column='preCod', primary_key=True, serialize=False, verbose_name='Codigo')),
                ('pretex', models.CharField(db_column='PreTex', max_length=300, verbose_name='Texto')),
                ('preestregcod', models.ForeignKey(db_column='PreEstRegCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.estadoregistro', verbose_name='Codigo EStReg')),
                ('preexacod', models.ForeignKey(db_column='PreExaCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.examen', verbose_name='Codigo EXamen')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Pregunta',
                'db_table': 'Pregunta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('altcod', models.AutoField(db_column='AltCod', primary_key=True, serialize=False, verbose_name='Codigo')),
                ('alttex', models.CharField(db_column='AltTex', max_length=500, verbose_name='Texto')),
                ('altcor', models.BooleanField(db_column='AltCor', verbose_name='Correcto')),
                ('altestregcod', models.ForeignKey(db_column='AltEstRegCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.estadoregistro', verbose_name='Codigo EstReg')),
                ('altprecod', models.ForeignKey(db_column='AltPreCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.pregunta', verbose_name='Codigo Pregunta')),
            ],
            options={
                'verbose_name': 'Alternativa',
                'verbose_name_plural': 'Alternativas',
                'db_table': 'alternativa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('procod', models.IntegerField(db_column='ProCod', primary_key=True, serialize=False, verbose_name='Codigo')),
                ('pronom', models.CharField(db_column='ProNom', max_length=100, verbose_name='Nombre')),
                ('procodosh', models.CharField(db_column='ProCodOsh', max_length=30, verbose_name='Codigo osha')),
                ('pronumhor', models.IntegerField(db_column='ProNumHor', default=0, verbose_name='Numero de horas')),
                ('pronumcur', models.IntegerField(db_column='ProNumCur', default=0, verbose_name='Numero de cursos')),
                ('cursos', models.ManyToManyField(blank=True, related_name='programas', to='aula.curso', verbose_name='Cursos')),
                ('proestregcod', models.ForeignKey(db_column='ProEstRegCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.estadoregistro', verbose_name='Codigo EstReg')),
            ],
            options={
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
                'db_table': 'programa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NotaPrograma',
            fields=[
                ('notprocod', models.AutoField(db_column='NotProCod', primary_key=True, serialize=False, verbose_name='codigo')),
                ('notpropun', models.DecimalField(db_column='NotProPun', decimal_places=2, max_digits=5, verbose_name='Puntuacion')),
                ('notproestcod', models.ForeignKey(db_column='NotProEstCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.estudiante', verbose_name='Codio Estudiante')),
                ('notproprocod', models.ForeignKey(db_column='NotProProCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.programa', verbose_name='Codigo Programa')),
            ],
            options={
                'verbose_name': 'NotaPrograma',
                'verbose_name_plural': 'NotaProgramas',
                'db_table': 'nota_programa',
                'managed': True,
                'unique_together': {('notproestcod', 'notproprocod')},
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('matcod', models.AutoField(db_column='MatCod', primary_key=True, serialize=False, verbose_name='Codigo')),
                ('matestcod', models.ForeignKey(db_column='MatEstCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.estudiante', verbose_name='Codigo Estudiante')),
                ('matestregcod', models.ForeignKey(db_column='MatEstRegCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.estadoregistro', verbose_name='Codigo EstReg')),
                ('matprocod', models.ForeignKey(db_column='MatProCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.programa', verbose_name='Codigo Programa')),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'Matriculas',
                'db_table': 'matricula',
                'managed': True,
                'unique_together': {('matestcod', 'matprocod')},
            },
        ),
        migrations.CreateModel(
            name='RegistroCurso',
            fields=[
                ('regcurcod', models.AutoField(db_column='RegCurCod', primary_key=True, serialize=False, verbose_name='Codigo')),
                ('regcurest', models.CharField(db_column='RegCurEst', max_length=50, verbose_name='Estado')),
                ('regcurpro', models.DecimalField(db_column='RegCurPro', decimal_places=2, max_digits=5, verbose_name='Progeso')),
                ('regcurcurcod', models.ForeignKey(db_column='RegCurCurCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.curso', verbose_name='Codigo Curso')),
                ('regcurestcod', models.ForeignKey(db_column='RegCurEstCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.estudiante', verbose_name='Codigo Estudiante')),
                ('regcurprocod', models.ForeignKey(db_column='RegCurProCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.programa', verbose_name='Codiogo Programa')),
            ],
            options={
                'verbose_name': 'RegistroCurso',
                'verbose_name_plural': 'RegistroCursos',
                'db_table': 'registro_curso',
                'managed': True,
                'unique_together': {('regcurprocod', 'regcurestcod', 'regcurcurcod')},
            },
        ),
        migrations.CreateModel(
            name='RegistroExamen',
            fields=[
                ('regexacod', models.AutoField(db_column='RegExaCod', primary_key=True, serialize=False, verbose_name='Codigo')),
                ('regexapun', models.DecimalField(db_column='RegExaPun', decimal_places=2, max_digits=5, verbose_name='Puntuacion')),
                ('regexaint', models.IntegerField(db_column='RegExaInt', default=0, verbose_name='Número de intentos')),
                ('regexaest', models.CharField(db_column='RegExaEst', max_length=100, verbose_name='Estado')),
                ('regexaestcod', models.ForeignKey(db_column='RegExaEstCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.estudiante', verbose_name='Codio Estudiante')),
                ('regexaexacod', models.ForeignKey(db_column='RegExaExaCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.examen', verbose_name='Codigo Examen')),
            ],
            options={
                'verbose_name': 'RegistroExamen',
                'verbose_name_plural': 'RegistroExamenes',
                'db_table': 'registro_examen',
                'managed': True,
                'unique_together': {('regexaestcod', 'regexaexacod')},
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('rescod', models.AutoField(db_column='ResCod', primary_key=True, serialize=False, verbose_name='Codigo')),
                ('respun', models.DecimalField(db_column='ResPun', decimal_places=2, max_digits=5, verbose_name='Puntuacion')),
                ('resaltcod', models.ForeignKey(db_column='ResAltCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.alternativa', verbose_name='Codigo Alternativa')),
                ('resestcod', models.ForeignKey(db_column='ResEstCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.estudiante', verbose_name='Codigo Estudiante')),
                ('resestregcod', models.ForeignKey(db_column='AltEstRegCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.estadoregistro', verbose_name='Codigo EstReg')),
                ('resexacod', models.ForeignKey(db_column='ResExaCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.examen', verbose_name='Codigo Examen')),
                ('resprecod', models.ForeignKey(db_column='ResPreCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.pregunta', verbose_name='Codigo Pregunta')),
                ('resprocod', models.ForeignKey(db_column='ResProCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.programa', verbose_name='Codigo Programa')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'db_table': 'respuesta',
                'managed': True,
                'unique_together': {('resestcod', 'resprocod', 'resexacod', 'resprecod')},
            },
        ),
    ]
