# Generated by Django 5.0.3 on 2024-07-26 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaprograma',
            name='notproestcod',
            field=models.ForeignKey(db_column='NotProEstCod', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Codio Estudiante'),
        ),
        migrations.AlterField(
            model_name='registroexamen',
            name='regexaestcod',
            field=models.ForeignKey(db_column='RegExaEstCod', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Codio Estudiante'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='resestcod',
            field=models.ForeignKey(db_column='ResEstCod', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Codigo Estudiante'),
        ),
        migrations.AlterField(
            model_name='registrocurso',
            name='regcurestcod',
            field=models.ForeignKey(db_column='RegCurEstCod', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Codigo Estudiante'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='curestregcod',
            field=models.ForeignKey(db_column='CurEstRegCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.estadoregistro', verbose_name='Codigo EstReg'),
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
