# Generated by Django 5.0.3 on 2024-04-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'managed': True, 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelTable(
            name='estudiante',
            table='estudiante',
        ),
    ]
