# Generated by Django 5.0.3 on 2024-03-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='cerestregcod',
        ),
        migrations.RemoveField(
            model_name='diploma',
            name='dipestregcod',
        ),
        migrations.DeleteModel(
            name='Carnet',
        ),
        migrations.DeleteModel(
            name='Certificado',
        ),
        migrations.DeleteModel(
            name='Diploma',
        ),
    ]
