# Generated by Django 5.0.3 on 2024-07-03 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='modestregcod',
            field=models.ForeignKey(db_column='ModEstRegCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.estadoregistro', verbose_name='Codigo EstReg'),
        ),
    ]
