# Generated by Django 5.0.3 on 2024-07-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_alter_modulo_modestregcod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternativa',
            old_name='altCor',
            new_name='altcor',
        ),
        migrations.AddField(
            model_name='programa',
            name='pronumhor',
            field=models.IntegerField(db_column='ProNumHor', default=0, verbose_name='Numero de horas'),
        ),
    ]
