# Generated by Django 5.0.3 on 2024-07-27 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_alter_notaprograma_notproestcod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoExamen',
            fields=[
                ('estexacod', models.AutoField(db_column='EstExaCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('estexanom', models.CharField(db_column='EstExaNom', max_length=40, unique=True, verbose_name='Nombre de Estado')),
            ],
            options={
                'verbose_name': 'EstadoExamen',
                'verbose_name_plural': 'EstadosExamenes',
                'db_table': 'estado_examen',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='registroexamen',
            name='regexaest',
        ),
        migrations.AlterField(
            model_name='registroexamen',
            name='regexaestcod',
            field=models.ForeignKey(db_column='RegExaEstCod', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Codigo Estudiante'),
        ),
        migrations.AddField(
            model_name='registroexamen',
            name='regexaestexacod',
            field=models.ForeignKey(blank=True, db_column='RegExaEstExaCod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aula.estadoexamen', verbose_name='Codigo Examen'),
        ),
    ]
