# Generated by Django 5.0.3 on 2024-07-30 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0003_estadoexamen_remove_registroexamen_regexaest_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registroexamen',
            unique_together=set(),
        ),
    ]
