# Generated by Django 5.0.3 on 2024-07-31 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0004_alter_registroexamen_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroexamen',
            name='regexaestprocod',
            field=models.ForeignKey(blank=True, db_column='RegExaEstProCod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aula.programa', verbose_name='Codigo Programa'),
        ),
        migrations.AlterUniqueTogether(
            name='registroexamen',
            unique_together={('regexaestprocod', 'regexaestcod', 'regexaexacod')},
        ),
    ]
