# Generated by Django 5.0.3 on 2024-07-31 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0005_registroexamen_regexaestprocod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='exacurcod',
            field=models.OneToOneField(db_column='ExaCurCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.curso', verbose_name='Codigo Curso'),
        ),
    ]
