# Generated by Django 5.0.3 on 2024-07-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0006_alter_examen_exacurcod'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='exanumpre',
            field=models.IntegerField(db_column='ExaNumPre', default=0, verbose_name='Numero de preguntas'),
        ),
    ]
