# Generated by Django 5.0.3 on 2024-08-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0007_examen_exanumpre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='prenummod',
            field=models.IntegerField(db_column='PreNumMod', default=0, verbose_name='Número de modulo'),
        ),
    ]
