# Generated by Django 5.0.3 on 2024-08-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0008_pregunta_prenummod'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='prenumsec',
            field=models.IntegerField(db_column='PreNumSec', default=0, verbose_name='Número de sección al que pertenece'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='prenummod',
            field=models.IntegerField(db_column='PreNumMod', default=0, verbose_name='Número de modulo al que pertenece'),
        ),
    ]
