# Generated by Django 5.0.3 on 2024-09-02 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0009_pregunta_prenumsec_alter_pregunta_prenummod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='exacod',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='resestregcod',
        ),
        migrations.AlterField(
            model_name='examen',
            name='exacurcod',
            field=models.OneToOneField(db_column='ExaCurCod', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='aula.curso', verbose_name='Codigo Curso'),
        ),
        migrations.AlterField(
            model_name='examen',
            name='exaestregcod',
            field=models.ForeignKey(db_column='ExaEstRegCod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aula.estadoregistro', verbose_name='Codigo EStReg'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='preexacod',
            field=models.ForeignKey(db_column='PreExaCod', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula.examen', verbose_name='Codigo EXamen'),
        ),
        migrations.AlterField(
            model_name='registroexamen',
            name='regexaexacod',
            field=models.ForeignKey(db_column='RegExaExaCod', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula.examen', verbose_name='Codigo Examen'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='resaltcod',
            field=models.ForeignKey(db_column='ResAltCod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aula.alternativa', verbose_name='Codigo Alternativa'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='resestcod',
            field=models.ForeignKey(db_column='ResEstCod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Codigo Estudiante'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='resexacod',
            field=models.ForeignKey(db_column='ResExaCod', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aula.examen', verbose_name='Codigo Examen'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='resprecod',
            field=models.ForeignKey(db_column='ResPreCod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aula.pregunta', verbose_name='Codigo Pregunta'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='resprocod',
            field=models.ForeignKey(db_column='ResProCod', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aula.programa', verbose_name='Codigo Programa'),
        ),
    ]
