# Generated by Django 5.0.3 on 2025-02-21 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificadoCursoMatriculado',
            fields=[
                ('cercurcod', models.AutoField(db_column='CerCurCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('cercurfecemi', models.DateField(blank=True, db_column='CerCurFecEmi', null=True, verbose_name='Fecha de emisión')),
                ('cercurfeccad', models.DateField(blank=True, db_column='CerCurFecCad', null=True, verbose_name='Fecha de caducidad')),
                ('cercurcarnet', models.BooleanField(db_column='CerCurCarnet', default=False, verbose_name='Con carnet')),
            ],
            options={
                'verbose_name': 'Certificado para Curso Matriculado',
                'verbose_name_plural': 'Certificados para Curso Matriculado',
                'db_table': 'certificado_curso_matriculado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CredencialPrograma',
            fields=[
                ('creprocod', models.AutoField(db_column='CreProCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('creprofecemi', models.DateField(blank=True, db_column='CreProFecEmi', null=True, verbose_name='Fecha de emisión')),
                ('creprofeccad', models.DateField(blank=True, db_column='CreProFecCad', null=True, verbose_name='Fecha de caducidad')),
                ('creprocer', models.BooleanField(db_column='CreProCer', default=True, verbose_name='Certificado')),
                ('creprodip', models.BooleanField(db_column='CreProDip', default=True, verbose_name='Con diploma')),
                ('creprocarnet', models.BooleanField(db_column='CreProCarnet', default=True, verbose_name='Con carnet')),
            ],
            options={
                'verbose_name': 'Credencial para Programa',
                'verbose_name_plural': 'Credenciales para Programa',
                'db_table': 'Credencial_programa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CredencialProgramaMatriculado',
            fields=[
                ('creprocod', models.AutoField(db_column='CreProCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('creprofecemi', models.DateField(blank=True, db_column='CreProFecEmi', null=True, verbose_name='Fecha de emisión')),
                ('creprofeccad', models.DateField(blank=True, db_column='CreProFecCad', null=True, verbose_name='Fecha de caducidad')),
                ('creprocer', models.BooleanField(db_column='CreProCer', default=True, verbose_name='Certificado')),
                ('creprodip', models.BooleanField(db_column='CreProDip', default=True, verbose_name='Con diploma')),
                ('creprocarnet', models.BooleanField(db_column='CreProCarnet', default=True, verbose_name='Con carnet')),
            ],
            options={
                'verbose_name': 'Credencial para Programa Matriculado',
                'verbose_name_plural': 'Credenciales para Programa Matriculado',
                'db_table': 'Credencial_programa_matriculado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CertificadoCurso',
            fields=[
                ('cercurcod', models.AutoField(db_column='CerCurCod', primary_key=True, serialize=False, verbose_name='Código')),
                ('cercurfecemi', models.DateField(blank=True, db_column='CerCurFecEmi', null=True, verbose_name='Fecha de emisión')),
                ('cercurfeccad', models.DateField(blank=True, db_column='CerCurFecCad', null=True, verbose_name='Fecha de caducidad')),
                ('cercurcarnet', models.BooleanField(db_column='CerCurCarnet', default=False, verbose_name='Con carnet')),
                ('cercurcurcod', models.ForeignKey(blank=True, db_column='CerCurCurCod', null=True, on_delete=django.db.models.deletion.PROTECT, to='aula.curso', verbose_name='Código Programa')),
            ],
            options={
                'verbose_name': 'Certificado para Curso',
                'verbose_name_plural': 'Certificados para Curso',
                'db_table': 'certificado_curso',
                'managed': True,
            },
        ),
    ]
