# Generated by Django 5.0.3 on 2024-05-11 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carnet',
            fields=[
                ('carcod', models.AutoField(db_column='CarCod', primary_key=True, serialize=False, verbose_name='')),
                ('carestregcod', models.ForeignKey(db_column='CarEstRegCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.estadoregistro', verbose_name='Codigo EstReg')),
            ],
            options={
                'verbose_name': 'Carnet',
                'verbose_name_plural': 'Carnets',
                'db_table': 'carnet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('cercod', models.AutoField(db_column='CerCod', primary_key=True, serialize=False, verbose_name='Codigo')),
                ('cerestregcod', models.ForeignKey(db_column='CerEstRegCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.estadoregistro', verbose_name='Codigo EstReg')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'db_table': 'certificado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('dipcod', models.AutoField(db_column='DipCod', primary_key=True, serialize=False, verbose_name='')),
                ('dipestregcod', models.ForeignKey(db_column='DipEstRegCod', on_delete=django.db.models.deletion.DO_NOTHING, to='aula.estadoregistro', verbose_name='Codigo EstReg')),
            ],
            options={
                'verbose_name': 'Diploma',
                'verbose_name_plural': 'Diplomas',
                'db_table': 'diploma',
                'managed': True,
            },
        ),
    ]
